// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appStatus: () => __TAURI_INVOKE<string>("app_status"),
	listCaptureModes: () => __TAURI_INVOKE<CaptureMode[]>("list_capture_modes"),
	shortcutStatus: () => __TAURI_INVOKE<ShortcutStatus[]>("shortcut_status"),
	effectiveShortcutAccelerators: () => __TAURI_INVOKE<{ [key in string]: string[] }>("effective_shortcut_accelerators"),
	cropCapture: (sourcePath: string, x: number, y: number, width: number, height: number) => typedError<CaptureResult, string>(__TAURI_INVOKE("crop_capture", { sourcePath, x, y, width, height })),
	cutoutCapture: (sourcePath: string, axis: string, start: number, length: number) => typedError<CaptureResult, string>(__TAURI_INVOKE("cutout_capture", { sourcePath, axis, start, length })),
	savePngBytes: (destPath: string, bytes: number[]) => typedError<null, string>(__TAURI_INVOKE("save_png_bytes", { destPath, bytes })),
	savePngBytesNew: (destPath: string, bytes: number[]) => typedError<boolean, string>(__TAURI_INVOKE("save_png_bytes_new", { destPath, bytes })),
	copyImageToClipboard: (path: string) => typedError<null, string>(__TAURI_INVOKE("copy_image_to_clipboard", { path })),
	copyPngBytesToClipboard: (bytes: number[]) => typedError<null, string>(__TAURI_INVOKE("copy_png_bytes_to_clipboard", { bytes })),
	revealInDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_dir", { path })),
	captureActiveWindow: () => typedError<CaptureResult, string>(__TAURI_INVOKE("capture_active_window")),
	screenRecordingAccess: () => __TAURI_INVOKE<boolean>("screen_recording_access"),
	openScreenRecordingSettings: () => typedError<null, string>(__TAURI_INVOKE("open_screen_recording_settings")),
	listDocuments: () => typedError<DocumentRecord[], string>(__TAURI_INVOKE("list_documents")),
	createDocument: (sourcePath: string, mode: string, title: string, width: number, height: number) => typedError<DocumentRecord, string>(__TAURI_INVOKE("create_document", { sourcePath, mode, title, width, height })),
	replaceDocumentBase: (id: string, sourcePath: string, title: string, width: number, height: number) => typedError<DocumentRecord, string>(__TAURI_INVOKE("replace_document_base", { id, sourcePath, title, width, height })),
	saveDocument: (id: string, annotations: string, currentPng: number[], dirty: boolean) => typedError<DocumentRecord, string>(__TAURI_INVOKE("save_document", { id, annotations, currentPng, dirty })),
	deleteDocument: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_document", { id })),
	getSettings: () => __TAURI_INVOKE<CaptureSettings>("get_settings"),
	updateSettings: (settings: CaptureSettings) => typedError<CaptureSettings, string>(__TAURI_INVOKE("update_settings", { settings })),
	resetShortcutSettings: () => typedError<CaptureSettings, string>(__TAURI_INVOKE("reset_shortcut_settings")),
	autostartEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("autostart_enabled")),
	setAutostart: (enabled: boolean) => typedError<boolean, string>(__TAURI_INVOKE("set_autostart", { enabled })),
	startRegionSelection: () => typedError<null, string>(__TAURI_INVOKE("start_region_selection")),
	finishRegionSelection: (selection: RegionSelection) => typedError<CaptureResult, string>(__TAURI_INVOKE("finish_region_selection", { selection })),
	cancelRegionSelection: () => typedError<null, string>(__TAURI_INVOKE("cancel_region_selection")),
	startWindowSelection: () => typedError<null, string>(__TAURI_INVOKE("start_window_selection")),
	finishWindowPointSelection: (x: number | null, y: number | null) => typedError<CaptureResult, string>(__TAURI_INVOKE("finish_window_point_selection", { x, y })),
	windowRectAtPoint: (x: number | null, y: number | null) => typedError<{
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
} | null, string>(__TAURI_INVOKE("window_rect_at_point", { x, y })),
	cancelWindowSelection: () => typedError<null, string>(__TAURI_INVOKE("cancel_window_selection")),
	startScreenSelection: () => typedError<null, string>(__TAURI_INVOKE("start_screen_selection")),
	/**
	 *  Capture the display under the mouse cursor immediately, with no picker UI.
	 * 
	 *  This is what the plain Screen hotkey does: because nothing is shown and no
	 *  focus is taken, a context menu (or other transient UI) open at the moment
	 *  the hotkey fires stays open and is captured — the original reason the
	 *  always-show-picker behaviour was a problem. The picker is still reachable on
	 *  its own hotkey (the `screen-pick` mode) and from the in-app Screen button.
	 */
	captureScreenUnderCursor: () => typedError<null, string>(__TAURI_INVOKE("capture_screen_under_cursor")),
	listScreensForSelection: () => typedError<CapturableMonitor[], string>(__TAURI_INVOKE("list_screens_for_selection")),
	finishScreenSelection: (monitorId: number) => typedError<CaptureResult, string>(__TAURI_INVOKE("finish_screen_selection", { monitorId })),
	cancelScreenSelection: () => typedError<null, string>(__TAURI_INVOKE("cancel_screen_selection")),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
};

/** Events */
export const events = {
	captureCancelled: makeEvent<CaptureCancelled>("capture-cancelled"),
	captureCompleted: makeEvent<CaptureCompleted>("capture-completed"),
	captureShortcut: makeEvent<CaptureShortcut>("capture-shortcut"),
	shortcutRegistration: makeEvent<ShortcutRegistration>("shortcut-registration"),
};

/* Types */
export type CapturableMonitor = {
	id: number,
	name: string,
	friendlyName: string,
	x: number,
	y: number,
	width: number,
	height: number,
	scaleFactor: number | null,
	primary: boolean,
};

export type CaptureCancelled = string;

export type CaptureCompleted = CaptureResult;

export type CaptureMode = {
	id: string,
	label: string,
	accelerators: string[],
};

export type CaptureResult = {
	mode: string,
	title: string,
	path: string,
	width: number,
	height: number,
};

export type CaptureSettings = {
	version?: number,
	saveDirectory?: string | null,
	copyToClipboard?: boolean,
	playCaptureSound?: boolean,
	autoOpenEditor?: boolean,
	bringToFrontOnHotkeyCapture?: boolean,
	closeToTray?: boolean,
	shortcutOverrides?: { [key in string]: string[] },
};

export type CaptureShortcut = string;

export type DocumentRecord = {
	id: string,
	mode: string,
	title: string,
	width: number,
	height: number,
	createdAt: number | null,
	updatedAt: number | null,
	dirty: boolean,
	basePath: string,
	currentPath: string,
	annotations: string,
};

export type RegionSelection = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
	scaleFactor: number | null,
};

export type ShortcutRegistration = ShortcutStatus;

export type ShortcutState = "registered" | "failed";

export type ShortcutStatus = {
	accelerator: string,
	mode: string,
	state: ShortcutState,
	error: string | null,
};

export type WindowBounds = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

